# Generated by Django 4.2 on 2025-09-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='touravailability',
            unique_together=set(),
        ),
    ]
