# Generated by Django 4.2 on 2025-09-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_touravailability_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourreview',
            unique_together=set(),
        ),
    ]
