# Generated by Django 4.2 on 2025-09-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_preferr_b62ce4_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='availability_description',
            field=models.CharField(default='Available all week', help_text="Description of tour availability (e.g., 'Available all week', 'Weekends only', etc.)", max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
